root: true
plugins:
  - react
extends:
  - plugin:react/recommended
  - prettier
parser: "@babel/eslint-parser"
env: {}
globals:
  __noteStatus__: true
  emit: true
rules:
  no-useless-escape: 0
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
